# First Source: Disparity Study QC

#### Analyst: Dhruv Singh <br> Report Name: Disparity Study <br> Report Quarter, Year: FY 2021 Q4 <br> Date Updated: 09/29/2021

In [3]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# reading in data
df = pd.read_csv('readonly/Disparity Report 9.28.21.csv')

In [5]:
df.head()

,Agreement Name,Project Name,Company Name,Contract Number,Estimated Start Date,Estimated End Date,Contact Person,Address 1,Address 2,City,...,Contracting Agency,NotSelfPerformingWork,DCSupplySchedule,IDIQ,MOBIS,PerformingWork,SupplyOnly,AlternativePlan,MonitoredById,Unnamed: 29
0,1000 F Street_American Automatic Sprinkler Com...,1000 F Street,"American Automatic Sprinkler Company, Inc.",NaN,3/1/2015,9/1/2015,Tahnie Boggess,"1000 F Street, NW",NaN,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,NaN,NaN
1,"1000 F Street_Berkel & Company Contractors, Inc.",1000 F Street,"Berkel & Company Contractors, Inc.",NaN,1/21/2015,5/22/2015,David Weatherer,"1000 F Street, NW",NaN,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,NaN,NaN
2,1000 F Street_Celtic Demolition,1000 F Street,Celtic Demolition,NaN,11/1/2014,6/1/2015,Ross Tumulty,"1000 F Street, NW",NaN,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,NaN,NaN
3,1000 F Street_Fort Myer Construction Corporation,1000 F Street,Fort Myer Construction Corporation,NaN,6/1/2016,10/1/2016,Mike Caro (TERMINATED EMPEE),"1000 F Street, NW",NaN,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,NaN,NaN
4,"1000 F Street_Goldin & Stafford, Inc.",1000 F Street,"Goldin & Stafford, Inc.",NaN,1/30/2015,7/16/2015,Vincent Shirbach,"1000 F Street, NW",NaN,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,NaN,NaN

In [7]:
df = df.fillna(0)

In [9]:
df.dtypes

Agreement Name            object
Project Name              object
Company Name              object
Contract Number           object
Estimated Start Date      object
Estimated End Date        object
Contact Person            object
Address 1                 object
Address 2                 object
City                      object
State                     object
Zip                        int64
Ward                      object
Contact Person Email      object
Contact Person Phone      object
 Contract Amount          object
Agreement Type            object
Agreement Name.1          object
Company Role              object
Agreement Status          object
Contracting Agency        object
NotSelfPerformingWork      int64
DCSupplySchedule           int64
IDIQ                       int64
MOBIS                      int64
PerformingWork             int64
SupplyOnly                 int64
AlternativePlan            int64
MonitoredById            float64
Unnamed: 29              float64
dtype: object

In [13]:
df.columns

Index(['Agreement Name', 'Project Name', 'Company Name', 'Contract Number',
       'Estimated Start Date', 'Estimated End Date', 'Contact Person',
       'Address 1', 'Address 2', 'City', 'State', 'Zip', 'Ward',
       'Contact Person Email', 'Contact Person Phone', ' Contract Amount ',
       'Agreement Type', 'Agreement Name.1', 'Company Role',
       'Agreement Status', 'Contracting Agency', 'NotSelfPerformingWork',
       'DCSupplySchedule', 'IDIQ', 'MOBIS', 'PerformingWork', 'SupplyOnly',
       'AlternativePlan', 'MonitoredById', 'Unnamed: 29'],
      dtype='object')

In [14]:
df[' Contract Amount ']

0           $274,000.00
1           $998,122.00
2           $250,000.00
3           $159,300.00
4           $479,000.00
              ...
3974        $700,000.00
3975      $1,094,076.00
3976        $989,931.00
3977        $400,000.00
3978     $61,139,833.00
Name:  Contract Amount , Length: 3979, dtype: object

In [15]:
df = df.rename(columns = {' Contract Amount ': 'Contract Amount'})

In [16]:
df['Contract Amount'] = df['Contract Amount'].str.replace('$','')

<ipython-input-16-c92a90048514>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['Contract Amount'] = df['Contract Amount'].str.replace('$','')

In [17]:
df['Contract Amount']

0           274,000.00
1           998,122.00
2           250,000.00
3           159,300.00
4           479,000.00
             ...
3974        700,000.00
3975      1,094,076.00
3976        989,931.00
3977        400,000.00
3978     61,139,833.00
Name: Contract Amount, Length: 3979, dtype: object

In [18]:
df['Contract Amount'] = df['Contract Amount'].str.replace(',','')

In [19]:
df['Contract Amount']

0          274000.00
1          998122.00
2          250000.00
3          159300.00
4          479000.00
            ...
3974       700000.00
3975      1094076.00
3976       989931.00
3977       400000.00
3978     61139833.00
Name: Contract Amount, Length: 3979, dtype: object

In [21]:
df['Contract Amount'] = df['Contract Amount'].str.replace(' ','')

In [22]:
df['Contract Amount'] = df['Contract Amount'].str.replace('-','')

In [23]:
df['Contract Amount']

0         274000.00
1         998122.00
2         250000.00
3         159300.00
4         479000.00
           ...
3974      700000.00
3975     1094076.00
3976      989931.00
3977      400000.00
3978    61139833.00
Name: Contract Amount, Length: 3979, dtype: object

In [24]:
df['Contract Amount'] = pd.to_numeric(df['Contract Amount'])

In [25]:
df['Contract Amount']

0         274000.0
1         998122.0
2         250000.0
3         159300.0
4         479000.0
           ...
3974      700000.0
3975     1094076.0
3976      989931.0
3977      400000.0
3978    61139833.0
Name: Contract Amount, Length: 3979, dtype: float64

In [28]:
df['Contract Amount'].describe()

count    3.952000e+03
mean     4.997137e+06
std      2.702429e+07
min      2.112000e+04
25%      3.999982e+05
50%      8.876125e+05
75%      2.168963e+06
max      1.098474e+09
Name: Contract Amount, dtype: float64

In [29]:
df[df['Contract Amount'] > 1000000000]

,Agreement Name,Project Name,Company Name,Contract Number,Estimated Start Date,Estimated End Date,Contact Person,Address 1,Address 2,City,...,Contracting Agency,NotSelfPerformingWork,DCSupplySchedule,IDIQ,MOBIS,PerformingWork,SupplyOnly,AlternativePlan,MonitoredById,Unnamed: 29
3405,Trusted Health Plan_ Managed Care Program,Managed Care Program- Trusted Health Plan,TRUSTED HEALTH PLAN,DHCF-2017-C-0024-A03,10/1/2018,9/1/2022,0,441 4th Street NW Suite 900 South,0,Washington,...,Department of Health Care Finance (DHCF),0,0,0,0,0,0,0,0.0,0.0

In [30]:
df = df.sort_values(by=['Project Name', 'Company Name'])

In [31]:
# outputting dups
dups = df[df.duplicated(subset = ['Project Name', 'Company Name'], keep=False)]

In [32]:
dups

,Agreement Name,Project Name,Company Name,Contract Number,Estimated Start Date,Estimated End Date,Contact Person,Address 1,Address 2,City,...,Contracting Agency,NotSelfPerformingWork,DCSupplySchedule,IDIQ,MOBIS,PerformingWork,SupplyOnly,AlternativePlan,MonitoredById,Unnamed: 29
2675,Human Care Agreement - Coastal Healthcare Serv...,Human Care Healthcare Agreement Direct Services,COASTAL HEALTHCARE SERVICES,CW38121,9/2/2017,9/1/2018,0,3801 Connecticut Ave NW,0,Washington,...,Office of the State Superintendent of Education,0,0,0,0,0,0,0,0.0,0.0
2676,Coastal Healthcare Services,Human Care Healthcare Agreement Direct Services,COASTAL HEALTHCARE SERVICES,DOC44052,2/10/2020,2/9/2021,0,810 First Street NE,0,Washington,...,Office of the State Superintendent of Education,0,0,0,0,0,0,0,0.0,0.0
2691,Tetra tech Inc.,2019 Anacostia River Sediment project,"TETRA TECH EM, INC.",CW67646,1/1/2019,1/1/2020,0,800 North Capitol Street NW Suite 760,0,Washington,...,Office of Contracting & Procurement (OCP),0,0,0,0,0,0,0,0.0,0.0
2692,Tetra Tech Inc._DOC385856,2019 Anacostia River Sediment project,"TETRA TECH EM, INC.",DOC385856,3/1/2019,1/30/2024,0,800 North Capitol Street NW Suite 760,0,Washington,...,Office of Contracting & Procurement (OCP),0,0,0,0,0,0,0,0.0,0.0
2701,801 East Operating,801 East Operating 1906CC801E,CATHOLIC CHARITIES OF ARCHDIOCESE OF Washingto...,1906CC801E,2/1/2019,1/31/2020,0,924 G STREET NW,0,Washington,...,THE COMMUNITY PARTNERSHIP FOR THE PREVENTION O...,0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,The Yards Parcel G-C.J. Coakley Company Interior,The Yards Parcel G,"C.J. Coakley Company, Inc.",0,7/24/2020,5/1/2021,0,1275 New Jersey Ave SE,0,Washington,...,Office of the Deputy Mayor for Planning and Ec...,0,0,0,0,0,0,0,0.0,0.0
857,Walter Reed Abrams Hall 14S-L.A. Howard Const...,Walter Reed Abrams Hall-14S,L.A. Howard Construction,0,5/1/2019,11/20/2019,0,1324 Main Drive NW,0,Washington,...,Department of Housing and Community Developmen...,0,0,0,0,0,0,0,0.0,0.0
858,Walter Reed Abrams Hall 14S-2-L.A. Construction,Walter Reed Abrams Hall-14S,L.A. Howard Construction,0,8/19/2018,10/20/2019,0,1324 Main Drive NW,0,Washington,...,Department of Housing and Community Developmen...,0,0,0,0,0,0,0,0.0,0.0
3307,1142 Buchanan St NW,information Technology Equipment and Software-...,Washington AREA NETWORK SERVICES LLC,CW57129,12/4/2017,12/4/2018,0,1142 Buchanan St NW,0,Washington,...,Office of Contracting & Procurement (OCP),0,0,0,0,0,0,0,0.0,0.0
3308,Washington Area Network Services LLC,information Technology Equipment and Software-...,Washington AREA NETWORK SERVICES LLC,DCSS-2006-R-91800,12/4/2017,12/4/2018,0,1142 Buchanan St NW,0,Washington,...,Office of Contracting & Procurement (OCP),0,0,0,0,0,0,0,0.0,0.0

In [33]:
dups.to_csv('data/duplicates.csv')

In [37]:
len(dups['Project Name'].unique())

58

In [38]:
len(dups['Company Name'].unique())

56